import Head from "next/head";
import Modal from "@/components/Modal";

//react icons
import { GiMoonBats } from "react-icons/gi";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { useState } from "react";

//to include an img in next you have to import the next/image component
import Image from "next/image";
import jslogo from "../../public/javascript-logo.svg";

export default function Home() {
  const [openModal, setOpenModal] = useState(false);

  return (
    <>
      <Head>
        <title>Octavian Busuioc Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <div className="flex gap-2">
              <h1 className="text-xl font-nunito">Js trooper</h1>
              <Image src={jslogo} alt="javascript logo" width={30} />
            </div>
            <ul className="flex items-center">
              <li>
                <GiMoonBats className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-fuchsia-800 to-violet-500 text-white px-4 py-2 rounded-md ml-4"
                  href="#"
                  onClick={() => setOpenModal(true)}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <Modal open={openModal} onClose={() => setOpenModal(false)}>
            fdsf
          </Modal>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-violet-700 font-semibold">
              Octavian Busuioc
            </h2>
            <h3 className="text-2xl py-2">Developer and web editor</h3>
            <p className="text-md py-5 leading-7 text-gray-600">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sed
              tincidunt purus. Maecenas molestie augue a consectetur pharetra.
              Etiam eu.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16">
            <AiFillGithub />
            <AiFillLinkedin />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-5 leading-7 text-gray-600">
              Lorem ipsum dolor sit amet, consectetur
              <span className="text-fuchsia-500">adipiscing elit</span>. Nunc
              sed tincidunt purus. Maecenas molestie
              <span className="text-fuchsia-500">augue a consectetur</span>
              pharetra. Etiam eu.
            </p>
            <p className="text-md py-5 leading-7 text-gray-600">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sed
              tincidunt purus. Maecenas molestie augue a consectetur pharetra.
              Etiam eu.
            </p>
          </div>
          <div>
            <div></div>
          </div>
        </section>
      </main>
    </>
  );
}
