
const data = {
    products: [
      {
        id: '1',
        name: 'Bouquet',
        price: 125,
        image: '/bouquet.png',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '2',
        name: 'Orange roses',
        price: 200,
        image: '/orange_roses.jpg',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '3',
        name: 'Bridal bouquet',
        price: 300,
        image: '/bridal_bouquet.jpg',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '4',
        name: 'Sunflower',
        price: 95,
        image: '/sunflower.png',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '5',
        name: 'Chrisantemum',
        price: 68,
        image: '/chrisantemum.jpg',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '6',
        name: 'Pink tulips',
        price: 90,
        image: '/pink_tulips.jpg',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '7',
        name: 'Sunflower',
        price: 75,
        image: '/sunflower.png',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '8',
        name: 'Colored roses',
        price: 200,
        image: '/colored_roses_bouquet.jpg',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '9',
        name: 'White roses',
        price: 175,
        image: '/white_roses.jpg',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '10',
        name: 'Roses basket',
        price: 300,
        image: '/sweet_tranquility_basket.png',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '11',
        name: 'White hidrangea',
        price: 300,
        image: '/white_hydrangea.png',
        basket_image: './basket_icon.jpg',
      },
      {
        id: '12',
        name: 'Wedding bouquet',
        price: 400,
        image: '/wed_bouquet.jpg',
        basket_image: './basket_icon.jpg',
      },
    ],
  };
  export default data;