
const data = {
    products: [
      {
        id: '1',
        name: 'Freesias',
        price: 125,
        image: '/freesias.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '2',
        name: 'Pink roses',
        price: 200,
        image: '/pink_roses.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '3',
        name: 'Gerbera & lilies',
        price: 300,
        image: '/gerbera_lilies.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '4',
        name: 'White roses and freesia',
        price: 95,
        image: '/white_roses_freesia.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '5',
        name: 'Chrisantemum',
        price: 68,
        image: '/chrisantemum.jpg',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '6',
        name: 'Pink tulips',
        price: 90,
        image: '/pink_tulips.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '7',
        name: 'Pink peonies',
        price: 75,
        image: '/pink_peonies.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '8',
        name: 'Red roses',
        price: 200,
        image: '/red_roses.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '9',
        name: 'White & pink roses',
        price: 175,
        image: '/white_pink_roses.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '10',
        name: 'White roses',
        price: 300,
        image: '/white_roses.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '11',
        name: 'White hidrangea',
        price: 300,
        image: '/white_hydrangea.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '12',
        name: 'Wedding bouquet',
        price: 400,
        image: '/wed_bouquet.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '13',
        name: 'Colored tulips',
        price: 40,
        image: '/colored_tulips.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '14',
        name: 'Roses',
        price: 400,
        image: '/pink_roses_2.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '15',
        name: 'White peonies',
        price: 30,
        image: '/white_peonies.png',
        basket_image: '/basket_icon.jpg',
      },
      {
        id: '16',
        name: 'Wedding bouquet',
        price: 400,
        image: '/wed_bouquet.png',
        basket_image: '/basket_icon.jpg',
      },
    ],
  };
  export default data;